[[asset]]
type = "safe_haven"
distributing = false
isin = "XS2115336336"
percentage = 10
allocated = 34.338

[[asset]]
type = "bond"
distributing = true
isin = "LU2504532487"
percentage = 35
allocated = 171.37

[[asset]]
type = "stock"
distributing = false
percentage = 55
allocated = 0

[[asset.subtype]]
type = "distributing"
distributing = true
isin = "IE00BFNM3C07"
percentage = 30
allocated = 73.9575

[[asset.subtype]]
type = "accumulating"
distributing = false
isin = "IE00BHZPJ569"
percentage = 70
allocated = 189.95
